### ISSUE TITLE
Option to disable star sign/chinese sign stuff

### ISSUE THREAD

**Issue by MatsG23** [m-i-n-a-r/birday#167] opened 2022-09-24 12:26 UTC
I have no clue why you would like to know the "chinese sign" (e.g. "Horse" :D) or star sign of a person.
Please allow to disable that stuff (that is spread here and there in the app).

**Comment by DominikNovosel** [comment] 2022-09-28 08:39
Duplicate of #59.

**Closed** 2022-10-26 10:06 UTC
