### ISSUE TITLE
Localization of date formats is not consistent

### ISSUE THREAD

**Issue by neubland** [m-i-n-a-r/birday#218] opened 2022-12-07 20:11 UTC
I use Birday in the German language.

For birthdays where there is a year, it is displayed correctly: "12. Dezember 1990"

For birthdays where there is no year, it is displayed in a weird and incorrect way (americanized?): "Dezember, 12"

But in the second case it should just as well be: "12. Dezember"

**Comment by m-i-n-a-r** [comment] 2022-12-07 23:06
Duplicate of #168, refer to it for further explanations 🙂 basically, there's no way (as far as I know) to consistently display a yearless date depending on the locale, so i use the same format. I'm open to suggestion, that's why I put the "help wanted" tag on the issue 👍

**Closed** 2022-12-07 23:07 UTC
Labels: duplicate
