### ISSUE TITLE
4.30 touching any contact freezes app

### ISSUE THREAD

**Issue by nutpantz** [m-i-n-a-r/birday#249] opened 2023-04-02 16:10 UTC
Latest from fdroid 4.30
Touching any contact freezes the app.
Android 12 aosp pixel 6

I changed setting advanced overview and now it seems to work. Still works when advanced overview turned off. No idea. I'll keep testing

**Comment by m-i-n-a-r** [comment] 2023-04-03 14:45
Well that's weird. "Advanced overview" simply activates the advanced overview screen, and nothing more. It shouldn't cause issues with the rest of the app, and i'm using this option with no issues on Android 12 and 13. Could you provide a log or something? Or maybe, test on another device? Thanks in advance!

**Comment by nutpantz** [comment] 2023-04-03 16:05
I tried on two other devices a similar update path and had no issues. No idea why it happened on the p6. Maybe it took some time to update the database and i was closing it to fast? I did force close it about 4 times after 30sec frozen until i tried changing settings

**Comment by m-i-n-a-r** [comment] 2023-04-04 07:47
The db should be updated in a couple seconds, and without freezing the UI, so I don't think it's the cause. I'll close this, but reopen it if you experience this issue on other devices 😄

**Closed by m-i-n-a-r** 2023-04-04 07:47 UTC
Labels: bug, help wanted
