### ISSUE TITLE
Import from Google Calendar

### ISSUE THREAD

**Issue by harimoradiya** [m-i-n-a-r/birday#137] opened 2022-05-09 16:08 UTC
It is possible to import events from google calendar with their API?

**Comment by m-i-n-a-r** [comment] 2022-05-10 09:50
Duplicate of #77 , but don't worry :)
The problem is, i wasn't able to use the API correctly to only select the birthdays, since there's no event type on Google Calendar (correct me if i'm wrong). It's on the to-do list, but i have no idea of how i should proceed.

**Comment by hari1412** [comment] 2022-05-10 09:58
Yes, there is no option to select a specific birthday day from the google calendar.
You are right:)

**Comment by hari1412** [comment] 2022-05-10 10:03
can I contribute in Hindi language?

**Comment by m-i-n-a-r** [comment] 2022-05-12 06:57
> can I contribute in Hindi language?

Yes, there's a guide in the wiki, follow it :) If you need help, send me an email

**Comment by hari1412** [comment] 2022-05-14 04:39
Okay

**Comment by m-i-n-a-r** [comment] 2022-11-21 21:46
I developed a basic calendar import in fd2dfc9fd1c969fe8a588904efe2453fe24aa25f and following commits. It works like in other apps (birthday calendar for instance). Basically, it finds any yearly event and imports it using the title as name and the description as note field. I can't, like other apps, recover the year and the type of the event. Feel free to open additional issues when you try this feature (should be available in next release)

**Closed** 2022-11-21 21:46 UTC
Labels: duplicate, enhancement
